### ISSUE TITLE
Add a new layout!

### ISSUE THREAD

**Issue by afred** [projecthydra/projecthydra.github.io#11]
**Background:** The current theme is pretty basic. We need one that can handle much more content, and looks pretty.

**Done when:**
  - [x] layout is decided upon. **UPDATE::** Use ["Knowledge-base"](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_kb_layout.html) layout
  - [x] theme is applied

**Comment by jenlindner** [comment]
We've got the theme working and a good start on content, ready for deployment.

**Comment by elrayle** [comment]
I believe that Issue #27, maintaining links to original training materials, needs to be resolved prior to deployment.

**Comment by jenlindner** [comment]
The original training materials don't need to live in the new theme, just be accessible from it, and so don't affect the criteria for deciding when the new layout is done.

**Comment by elrayle** [comment]
There is a conflict between the new jekyll template and the use of the deck layout.  This is described in Issue #27.
