### ISSUE TITLE
Add Lynette's tutorial for Customizing Metadata in Hyrax is added

### ISSUE THREAD

**Issue by afred** [projecthydra/projecthydra.github.io#12]
**Background:** Original tutorial is here: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata

This needs to be modified to apply to Hyrax (as opposed to Sufia).

Also, we need to identify a good location for where it should live within the layout.

**Done when:**
  - [x] Tutorial has been modified to apply to Hyrax.
  - [x] Content has been added to the appropriate location.

**Comment by elrayle** [comment]
Addressed by PR #35

**Comment by jenlindner** [comment]
Deployed.
