### ISSUE TITLE
Lesson about search builders

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/projecthydra.github.io#25]
Blacklight generates `app/models/search_builder.rb` into your application. It defaults to including `Blacklight::Solr::SearchBuilderBehavior` which are functions to allow blacklight to talk to solr (vs another search engine).  Hydra generates `include Hydra::AccessControlsEnforcement` for filtering
searches by access (groups & users).  Finally Hyrax generates `include Hyrax::SearchFilters` which overrides the hydra filters and allows users with the admin role to see all documents.

Hyrax then sets the `blacklight_config.config.search_builder_class = Hyrax::CatalogSearchBuilder` in the catalog controller. This enables the public search to not show works that are suppressed (in workflow) and to find a work if an attached file matches the search query.

Hyrax::CatalogSearchBuilder inherits from Hyrax::SearchBuilder
https://github.com/projecthydra-labs/hyrax/blob/master/app/search_builders/hyrax/catalog_search_builder.rb  (This class should be removed because it's basically the same as `::SearchBuilder`)

Hyrax::SearchBuilder inherits from Blacklight::SearchBuilder
https://github.com/projecthydra-labs/hyrax/blob/master/app/search_builders/hyrax/search_builder.rb

Blacklight::SearchBuilder is a plain old Ruby object
https://github.com/projectblacklight/blacklight/blob/v6.8.0/lib/blacklight/search_builder.rb

**Comment by jrochkind** [comment]
Related discussion on how things that inherit from `Hyrax::SearchBuilder ` aren't customizable via usual BL methods of customizing ::SearchBuilder, and it's unclear what the intended story for customization is. 

https://github.com/projecthydra-labs/hyrax/issues/707

@jcoyne , if you wanted to chime in there on what was intended here, what was a mistake what was not etc, what was the intention, to the extent you know, it would be helpful!

**Comment by jcoyne** [comment]
@jrochkind the intent is for this to be a first draft of some documentation about the Search builder. Feel free to note some things here, but the idea is that this would become a webpage once this branch is merged: https://github.com/projecthydra/projecthydra.github.io/tree/refactor_docs

Revisions might be easier after that point.

**Comment by jenlindner** [comment]
So, we have a how and why intro to customizing Search Builders and their ancestry structure, here: https://github.com/projecthydra/curation_concerns/wiki/Solr-Search-Builders. We plan to keep all docs like this under developer resources.

We also have a page/section for how searches work generally in our new docs, here: https://github.com/projecthydra/projecthydra.github.io/blob/refactor_docs/pages/hydra/developer_resources/what-happens-search.md

I'll make incorporating the customizing Search content into the developer resources section a high-priority action item. Do you want a page for what a better inheritance model of Search could look like? If yes, we'll make an action item of it - and it might be that a section on refactoring could add to the docs. Anyone interested could add that to the CfP for the docs working group. @jcoyne @jrochkind @atz

**Comment by jcoyne** [comment]
@jenlindner the wiki page in CC looks great. I didn't know it existed.  It would be great to pull that in here.

**Comment by jenlindner** [comment]
Deployed.
