### ISSUE TITLE
publish refactor_docs branch

### ISSUE THREAD

**Issue by jenlindner** [projecthydra/projecthydra.github.io#38]

**Comment by elrayle** [comment]
I believe that Issue #27, maintaining links to original training materials, needs to be resolved prior to deployment.

**Comment by jenlindner** [comment]
The original training materials don't need to live in the new theme, just be accessible from it. @jcoyne if you want to move the training docs to a location and add links to them in getting_started.md this weekend, that would address @elrayle's concern.

**Comment by jenlindner** [comment]
Deployed.
